name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.0-rc.1
    
    - name: test
      run: go test -coverprofile=coverage1.txt -covermode=atomic ./...

    - name: fuzz
      run: go test -coverprofile=coverage2.txt -covermode=atomic --fuzz-time=10s ./algo

    - name: merge coverage
      run: cat coverage1.txt coverage2.txt > coverage.txt

    - name: report coverage
      run: bash <(curl -s https://codecov.io/bash)

