name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: test
      run: go test -coverprofile=coverage1.txt -covermode=atomic ./...

    - name: fuzz
      run: go test -coverprofile=coverage2.txt -covermode=atomic ./algo --fuzz-time=5m

    - name: upload codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage1.txt, ./coverage2.txt

